<?xml version="1.0" encoding="utf-8"?><Database Name="tvl" Class="TVL_DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MATTHEW-PC\SQLSVR2014;Initial Catalog=tvl;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="tvlConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tPerson" Member="Persons">
    <Type Name="Person">
      <Column Name="PersonKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BillingAddressKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AltEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="AltPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="Inactive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByPersonKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedByPersonKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SourceKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceDetail" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tSource" Member="Sources">
    <Type Name="Source">
      <Column Name="SourceKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SourceName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Inactive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tUser" Member="Users">
    <Type Name="User">
      <Column Name="UserKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByPersonKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedByPersonKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Inactive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>